//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decidehub.Web.Resources.Controllers.Api {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiPollController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiPollController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Decidehub.Web.Resources.Controllers.Api.ApiPollController", typeof(ApiPollController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmiş oylamalar kaldırılamaz.
        /// </summary>
        public static string CantRemoveCompletedPoll {
            get {
                return ResourceManager.GetString("CantRemoveCompletedPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk yetki dağılım oylaması henüz başlatılmadı..
        /// </summary>
        public static string FirstAuthorityPollHaventStarted {
            get {
                return ResourceManager.GetString("FirstAuthorityPollHaventStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk paylaşım oylaması henüz başlatılmadı..
        /// </summary>
        public static string FirstSharePollHaventStarted {
            get {
                return ResourceManager.GetString("FirstSharePollHaventStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Oylama mevcuttur..
        /// </summary>
        public static string HasActivePoll {
            get {
                return ResourceManager.GetString("HasActivePoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adlı oylamada oy kullanmaya çağırıyor..
        /// </summary>
        public static string InvitedYouToVote {
            get {
                return ResourceManager.GetString("InvitedYouToVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adlı kullanıcı sizi.
        /// </summary>
        public static string NamedUser {
            get {
                return ResourceManager.GetString("NamedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oylama bitmiştir.
        /// </summary>
        public static string PollCompleted {
            get {
                return ResourceManager.GetString("PollCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oylama Daveti.
        /// </summary>
        public static string PollInvitation {
            get {
                return ResourceManager.GetString("PollInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oylama bulunamadı..
        /// </summary>
        public static string PollNotFound {
            get {
                return ResourceManager.GetString("PollNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oylama kaldırılırken bir hata meydana geldi..
        /// </summary>
        public static string RemovePollError {
            get {
                return ResourceManager.GetString("RemovePollError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oylamayı yalnızca oluşturan kişi kaldırabilir..
        /// </summary>
        public static string RemovePollUserError {
            get {
                return ResourceManager.GetString("RemovePollUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaşım oylaması aktif değil..
        /// </summary>
        public static string SharePollIsNotActive {
            get {
                return ResourceManager.GetString("SharePollIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Oylama Tipi.
        /// </summary>
        public static string UnknownPoll {
            get {
                return ResourceManager.GetString("UnknownPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyunuz sıfırlanırken bir hata meydana geldi..
        /// </summary>
        public static string VoteResetError {
            get {
                return ResourceManager.GetString("VoteResetError", resourceCulture);
            }
        }
    }
}
